// Merchant name cleaner + logo domain resolver

const MERCHANT_MAP: [RegExp, string][] = [
  [/netflix/i, "Netflix"],
  [/spotify/i, "Spotify"],
  [/amazon|amzn/i, "Amazon"],
  [/wal.?mart/i, "Walmart"],
  [/\btarget\b/i, "Target"],
  [/apple\.com|apple.*bill|itunes/i, "Apple"],
  [/\bhulu\b/i, "Hulu"],
  [/disney\+|disneyplus/i, "Disney+"],
  [/\bhbo\b|max\.com/i, "HBO Max"],
  [/paramount\+|paramountplus/i, "Paramount+"],
  [/peacock/i, "Peacock"],
  [/youtube premium/i, "YouTube Premium"],
  [/\byoutube\b/i, "YouTube"],
  [/google one|google storage/i, "Google One"],
  [/\bgoogle\b/i, "Google"],
  [/microsoft 365|microsoft office/i, "Microsoft 365"],
  [/microsoft/i, "Microsoft"],
  [/adobe/i, "Adobe"],
  [/github/i, "GitHub"],
  [/dropbox/i, "Dropbox"],
  [/\bzoom\b/i, "Zoom"],
  [/\bslack\b/i, "Slack"],
  [/openai|chatgpt/i, "ChatGPT"],
  [/\bvenmo\b/i, "Venmo"],
  [/paypal/i, "PayPal"],
  [/cash app|cashapp/i, "Cash App"],
  [/\bzelle\b/i, "Zelle"],
  [/uber eats/i, "Uber Eats"],
  [/\buber\b/i, "Uber"],
  [/\blyft\b/i, "Lyft"],
  [/doordash/i, "DoorDash"],
  [/grubhub/i, "GrubHub"],
  [/instacart/i, "Instacart"],
  [/postmates/i, "Postmates"],
  [/chipotle/i, "Chipotle"],
  [/mcdonald/i, "McDonald's"],
  [/starbucks/i, "Starbucks"],
  [/chick.fil.a/i, "Chick-fil-A"],
  [/dunkin/i, "Dunkin'"],
  [/\bsubway\b/i, "Subway"],
  [/domino/i, "Domino's"],
  [/pizza hut/i, "Pizza Hut"],
  [/taco bell/i, "Taco Bell"],
  [/burger king/i, "Burger King"],
  [/wendy/i, "Wendy's"],
  [/whole foods/i, "Whole Foods"],
  [/trader joe/i, "Trader Joe's"],
  [/\bkroger\b/i, "Kroger"],
  [/\bcostco\b/i, "Costco"],
  [/sam.?s club/i, "Sam's Club"],
  [/\bcvs\b/i, "CVS"],
  [/walgreens/i, "Walgreens"],
  [/rite aid/i, "Rite Aid"],
  [/7.eleven/i, "7-Eleven"],
  [/\bshell\b/i, "Shell"],
  [/chevron/i, "Chevron"],
  [/\bexxon\b/i, "Exxon"],
  [/\bbp\b/i, "BP"],
  [/sunoco/i, "Sunoco"],
  [/at&t|att\b/i, "AT&T"],
  [/verizon/i, "Verizon"],
  [/t.?mobile/i, "T-Mobile"],
  [/comcast|xfinity/i, "Xfinity"],
  [/\bspectrum\b/i, "Spectrum"],
  [/\bgeico\b/i, "GEICO"],
  [/state farm/i, "State Farm"],
  [/allstate/i, "Allstate"],
  [/progressive/i, "Progressive"],
  [/\bairbnb\b/i, "Airbnb"],
  [/expedia/i, "Expedia"],
  [/\bdelta\b/i, "Delta"],
  [/american airlines|aa\b/i, "American Airlines"],
  [/united airlines/i, "United Airlines"],
  [/southwest/i, "Southwest"],
  [/linkedin/i, "LinkedIn"],
  [/twitter|x\.com/i, "X (Twitter)"],
  [/facebook|meta\b/i, "Meta"],
  [/instagram/i, "Instagram"],
  [/tiktok/i, "TikTok"],
  [/peloton/i, "Peloton"],
  [/planet fitness/i, "Planet Fitness"],
  [/la fitness/i, "LA Fitness"],
  [/crunch fitness/i, "Crunch Fitness"],
  [/duolingo/i, "Duolingo"],
  [/audible/i, "Audible"],
  [/kindle/i, "Kindle"],
  [/\btwitch\b/i, "Twitch"],
  [/playstation|psn/i, "PlayStation"],
  [/xbox|game pass/i, "Xbox"],
  [/nintendo/i, "Nintendo"],
  [/steam\b/i, "Steam"],
  [/chewy/i, "Chewy"],
  [/etsy/i, "Etsy"],
  [/shopify/i, "Shopify"],
  [/notion/i, "Notion"],
  [/figma/i, "Figma"],
  [/canva/i, "Canva"],
  [/grammarly/i, "Grammarly"],
  [/lastpass/i, "LastPass"],
  [/1password/i, "1Password"],
  [/nordvpn/i, "NordVPN"],
  [/expressvpn/i, "ExpressVPN"],
  [/icloud/i, "iCloud"],
];

// Maps clean merchant name → domain for Clearbit logo
export const MERCHANT_DOMAINS: Record<string, string> = {
  "Netflix": "netflix.com",
  "Spotify": "spotify.com",
  "Amazon": "amazon.com",
  "Walmart": "walmart.com",
  "Target": "target.com",
  "Apple": "apple.com",
  "Hulu": "hulu.com",
  "Disney+": "disneyplus.com",
  "HBO Max": "max.com",
  "Paramount+": "paramountplus.com",
  "Peacock": "peacocktv.com",
  "YouTube": "youtube.com",
  "YouTube Premium": "youtube.com",
  "Google": "google.com",
  "Google One": "one.google.com",
  "Microsoft": "microsoft.com",
  "Microsoft 365": "microsoft.com",
  "Adobe": "adobe.com",
  "GitHub": "github.com",
  "Dropbox": "dropbox.com",
  "Zoom": "zoom.us",
  "Slack": "slack.com",
  "ChatGPT": "openai.com",
  "Venmo": "venmo.com",
  "PayPal": "paypal.com",
  "Cash App": "cash.app",
  "Uber Eats": "ubereats.com",
  "Uber": "uber.com",
  "Lyft": "lyft.com",
  "DoorDash": "doordash.com",
  "GrubHub": "grubhub.com",
  "Instacart": "instacart.com",
  "Chipotle": "chipotle.com",
  "McDonald's": "mcdonalds.com",
  "Starbucks": "starbucks.com",
  "Chick-fil-A": "chick-fil-a.com",
  "Dunkin'": "dunkindonuts.com",
  "Subway": "subway.com",
  "Domino's": "dominos.com",
  "Pizza Hut": "pizzahut.com",
  "Taco Bell": "tacobell.com",
  "Burger King": "bk.com",
  "Wendy's": "wendys.com",
  "Whole Foods": "wholefoodsmarket.com",
  "Trader Joe's": "traderjoes.com",
  "Kroger": "kroger.com",
  "Costco": "costco.com",
  "Sam's Club": "samsclub.com",
  "CVS": "cvs.com",
  "Walgreens": "walgreens.com",
  "Rite Aid": "riteaid.com",
  "7-Eleven": "7-eleven.com",
  "Shell": "shell.com",
  "Chevron": "chevron.com",
  "Exxon": "exxon.com",
  "BP": "bp.com",
  "Sunoco": "sunoco.com",
  "AT&T": "att.com",
  "Verizon": "verizon.com",
  "T-Mobile": "t-mobile.com",
  "Xfinity": "xfinity.com",
  "Spectrum": "spectrum.com",
  "GEICO": "geico.com",
  "State Farm": "statefarm.com",
  "Allstate": "allstate.com",
  "Progressive": "progressive.com",
  "Airbnb": "airbnb.com",
  "Expedia": "expedia.com",
  "Delta": "delta.com",
  "American Airlines": "aa.com",
  "United Airlines": "united.com",
  "Southwest": "southwest.com",
  "LinkedIn": "linkedin.com",
  "X (Twitter)": "x.com",
  "Meta": "meta.com",
  "TikTok": "tiktok.com",
  "Peloton": "onepeloton.com",
  "Planet Fitness": "planetfitness.com",
  "LA Fitness": "lafitness.com",
  "Duolingo": "duolingo.com",
  "Audible": "audible.com",
  "Twitch": "twitch.tv",
  "PlayStation": "playstation.com",
  "Xbox": "xbox.com",
  "Nintendo": "nintendo.com",
  "Steam": "store.steampowered.com",
  "Chewy": "chewy.com",
  "Etsy": "etsy.com",
  "Notion": "notion.so",
  "Figma": "figma.com",
  "Canva": "canva.com",
  "Grammarly": "grammarly.com",
  "NordVPN": "nordvpn.com",
  "ExpressVPN": "expressvpn.com",
  "iCloud": "icloud.com",
  "1Password": "1password.com",
};

export function simplifyName(raw: string | null | undefined): string {
  if (!raw) return "Unknown";

  // Check known merchant patterns first
  for (const [pattern, cleanName] of MERCHANT_MAP) {
    if (pattern.test(raw)) return cleanName;
  }

  // Generic cleanup for unknown merchants
  let clean = raw
    .replace(/\*/g, " ")
    .replace(/\b\d{7,}\b/g, "")           // remove phone numbers
    .replace(/\s+#\d+/g, "")             // remove store numbers #1234
    .replace(/\.(com|net|org|io)\b/gi, "") // remove TLDs
    .replace(/\b(LLC|INC|CORP|LTD|CO)\b\.?/gi, "")
    .replace(/\s{2,}/g, " ")
    .trim();

  // Title case
  return clean
    .split(" ")
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ") || raw;
}

export function getMerchantDomain(cleanName: string): string | null {
  return MERCHANT_DOMAINS[cleanName] ?? null;
}
