// Merchant name cleaner + logo domain resolver

const MERCHANT_MAP: [RegExp, string][] = [
  // ── Streaming & Entertainment ─────────────────────────────────────────────
  [/netflix/i, "Netflix"],
  [/\bhulu\b/i, "Hulu"],
  [/disney\+|disneyplus/i, "Disney+"],
  [/\bhbo\b|max\.com/i, "HBO Max"],
  [/paramount\+|paramountplus/i, "Paramount+"],
  [/peacock/i, "Peacock"],
  [/crunchyroll/i, "Crunchyroll"],
  [/\bstarz\b/i, "Starz"],
  [/showtime/i, "Showtime"],
  [/discovery\+|discoveryplus/i, "Discovery+"],
  [/\bfubo\b|fubutv/i, "Fubo"],
  [/sling tv|slingtv/i, "Sling TV"],
  [/youtube premium/i, "YouTube Premium"],
  [/\byoutube\b/i, "YouTube"],
  [/\btwitch\b/i, "Twitch"],
  [/\bplex\b/i, "Plex"],
  [/espn\+|espnplus/i, "ESPN+"],
  [/apple tv\+|apple.*tv/i, "Apple TV+"],
  [/\bshudder\b/i, "Shudder"],
  [/mubi/i, "MUBI"],

  // ── Music ─────────────────────────────────────────────────────────────────
  [/spotify/i, "Spotify"],
  [/apple music/i, "Apple Music"],
  [/amazon music/i, "Amazon Music"],
  [/tidal/i, "Tidal"],
  [/pandora/i, "Pandora"],
  [/sirius.*xm|siriusxm/i, "SiriusXM"],
  [/deezer/i, "Deezer"],
  [/soundcloud/i, "SoundCloud"],

  // ── Cloud & Apple ─────────────────────────────────────────────────────────
  [/icloud/i, "iCloud"],
  [/apple\.com|apple.*bill|itunes/i, "Apple"],
  [/google one|google storage/i, "Google One"],
  [/\bgoogle\b/i, "Google"],
  [/microsoft 365|microsoft office/i, "Microsoft 365"],
  [/microsoft/i, "Microsoft"],
  [/dropbox/i, "Dropbox"],
  [/box\.com/i, "Box"],
  [/onedrive/i, "OneDrive"],

  // ── Software & Productivity ───────────────────────────────────────────────
  [/adobe/i, "Adobe"],
  [/github/i, "GitHub"],
  [/\bzoom\b/i, "Zoom"],
  [/\bslack\b/i, "Slack"],
  [/notion/i, "Notion"],
  [/figma/i, "Figma"],
  [/canva/i, "Canva"],
  [/grammarly/i, "Grammarly"],
  [/lastpass/i, "LastPass"],
  [/1password/i, "1Password"],
  [/dashlane/i, "Dashlane"],
  [/nordvpn/i, "NordVPN"],
  [/expressvpn/i, "ExpressVPN"],
  [/surfshark/i, "Surfshark"],
  [/openai|chatgpt/i, "ChatGPT"],
  [/midjourney/i, "Midjourney"],
  [/\basana\b/i, "Asana"],
  [/\btrello\b/i, "Trello"],
  [/monday\.com/i, "Monday.com"],
  [/salesforce/i, "Salesforce"],
  [/hubspot/i, "HubSpot"],
  [/mailchimp/i, "Mailchimp"],
  [/squarespace/i, "Squarespace"],
  [/wix\.com/i, "Wix"],
  [/wordpress|wpengine/i, "WordPress"],
  [/godaddy/i, "GoDaddy"],
  [/namecheap/i, "Namecheap"],
  [/cloudflare/i, "Cloudflare"],
  [/\bheroku\b/i, "Heroku"],
  [/digitalocean/i, "DigitalOcean"],
  [/\baws\b|amazon web services/i, "AWS"],
  [/shopify/i, "Shopify"],
  [/duolingo/i, "Duolingo"],
  [/audible/i, "Audible"],
  [/kindle/i, "Kindle"],
  [/skillshare/i, "Skillshare"],
  [/masterclass/i, "MasterClass"],
  [/coursera/i, "Coursera"],
  [/udemy/i, "Udemy"],
  [/linkedin.*learn|linkedin/i, "LinkedIn"],

  // ── Gaming ────────────────────────────────────────────────────────────────
  [/playstation|psn/i, "PlayStation"],
  [/xbox|game pass/i, "Xbox"],
  [/nintendo/i, "Nintendo"],
  [/steam\b/i, "Steam"],
  [/epic games/i, "Epic Games"],
  [/battle\.net|blizzard/i, "Blizzard"],
  [/\bea\b.*play|electronic arts/i, "EA"],
  [/ubisoft|uplay/i, "Ubisoft"],

  // ── Payments & Finance ────────────────────────────────────────────────────
  [/\bvenmo\b/i, "Venmo"],
  [/paypal/i, "PayPal"],
  [/cash app|cashapp/i, "Cash App"],
  [/\bzelle\b/i, "Zelle"],
  [/klarna/i, "Klarna"],
  [/afterpay/i, "Afterpay"],
  [/affirm/i, "Affirm"],
  [/coinbase/i, "Coinbase"],
  [/robinhood/i, "Robinhood"],
  [/fidelity/i, "Fidelity"],
  [/schwab/i, "Charles Schwab"],
  [/vanguard/i, "Vanguard"],
  [/betterment/i, "Betterment"],
  [/wealthfront/i, "Wealthfront"],
  [/sofi/i, "SoFi"],
  [/acorns/i, "Acorns"],
  [/stash\b/i, "Stash"],

  // ── Banks ─────────────────────────────────────────────────────────────────
  [/\bchase\b/i, "Chase"],
  [/bank of america|bofa/i, "Bank of America"],
  [/wells fargo/i, "Wells Fargo"],
  [/capital one/i, "Capital One"],
  [/discover/i, "Discover"],
  [/\bciti\b|citibank/i, "Citi"],
  [/american express|amex/i, "Amex"],
  [/us bank|u\.s\. bank/i, "US Bank"],
  [/pnc bank|pnc\b/i, "PNC"],
  [/td bank/i, "TD Bank"],
  [/ally bank|ally financial/i, "Ally"],
  [/synchrony/i, "Synchrony"],

  // ── Ride Share & Delivery ─────────────────────────────────────────────────
  [/uber eats/i, "Uber Eats"],
  [/\buber\b/i, "Uber"],
  [/\blyft\b/i, "Lyft"],
  [/doordash/i, "DoorDash"],
  [/grubhub/i, "GrubHub"],
  [/instacart/i, "Instacart"],
  [/postmates/i, "Postmates"],
  [/gopuff/i, "GoPuff"],
  [/shipt/i, "Shipt"],
  [/\bfetch\b/i, "Fetch"],

  // ── Restaurants (Fast Food) ───────────────────────────────────────────────
  [/chipotle/i, "Chipotle"],
  [/mcdonald/i, "McDonald's"],
  [/starbucks/i, "Starbucks"],
  [/chick.fil.a/i, "Chick-fil-A"],
  [/dunkin/i, "Dunkin'"],
  [/\bsubway\b/i, "Subway"],
  [/domino/i, "Domino's"],
  [/pizza hut/i, "Pizza Hut"],
  [/taco bell/i, "Taco Bell"],
  [/burger king/i, "Burger King"],
  [/wendy/i, "Wendy's"],
  [/panda express/i, "Panda Express"],
  [/popeyes/i, "Popeyes"],
  [/sonic drive/i, "Sonic"],
  [/wingstop/i, "Wingstop"],
  [/shake shack/i, "Shake Shack"],
  [/five guys/i, "Five Guys"],
  [/whataburger/i, "Whataburger"],
  [/in.n.out/i, "In-N-Out"],
  [/jack in the box/i, "Jack in the Box"],
  [/arby/i, "Arby's"],
  [/hardee|carl.?s jr/i, "Hardee's"],
  [/checkers|rally/i, "Checkers"],
  [/del taco/i, "Del Taco"],
  [/qdoba/i, "Qdoba"],
  [/moe.?s southwest/i, "Moe's"],
  [/panera/i, "Panera Bread"],
  [/jersey mike/i, "Jersey Mike's"],
  [/firehouse subs/i, "Firehouse Subs"],
  [/jimmy john/i, "Jimmy John's"],
  [/\bkfc\b|kentucky fried/i, "KFC"],

  // ── Restaurants (Sit-Down & Chains) ──────────────────────────────────────
  [/olive garden/i, "Olive Garden"],
  [/applebee/i, "Applebee's"],
  [/\bihop\b/i, "IHOP"],
  [/\bdenny/i, "Denny's"],
  [/\bwaffle house/i, "Waffle House"],
  [/buffalo wild wings|bdubs/i, "Buffalo Wild Wings"],
  [/outback steakhouse|outback/i, "Outback"],
  [/red lobster/i, "Red Lobster"],
  [/texas roadhouse/i, "Texas Roadhouse"],
  [/longhorn steakhouse/i, "LongHorn"],
  [/red robin/i, "Red Robin"],
  [/\bchilis\b|chili.?s/i, "Chili's"],
  [/\btgi friday/i, "TGI Fridays"],
  [/cracker barrel/i, "Cracker Barrel"],
  [/perkins/i, "Perkins"],
  [/\bnoodles\b/i, "Noodles & Co"],
  [/the cheesecake factory|cheesecake factory/i, "Cheesecake Factory"],

  // ── Coffee & Cafes ────────────────────────────────────────────────────────
  [/dutch bros/i, "Dutch Bros"],
  [/coffee bean/i, "Coffee Bean"],
  [/peet.?s coffee/i, "Peet's"],
  [/caribou coffee/i, "Caribou Coffee"],
  [/tim hortons/i, "Tim Hortons"],

  // ── Grocery & Retail ─────────────────────────────────────────────────────
  [/whole foods/i, "Whole Foods"],
  [/trader joe/i, "Trader Joe's"],
  [/\bkroger\b/i, "Kroger"],
  [/\bcostco\b/i, "Costco"],
  [/sam.?s club/i, "Sam's Club"],
  [/\baldi\b/i, "Aldi"],
  [/\bpublix\b/i, "Publix"],
  [/\bh.e.b\b|heb grocery/i, "H-E-B"],
  [/\bmeijer\b/i, "Meijer"],
  [/\bwegman/i, "Wegmans"],
  [/\bsafeway\b/i, "Safeway"],
  [/\balbertson/i, "Albertsons"],
  [/\bvons\b/i, "Vons"],
  [/\bfood lion/i, "Food Lion"],
  [/\bgiant\b.*food|giant food/i, "Giant"],
  [/stop.?&.?shop/i, "Stop & Shop"],
  [/\bsprouts\b/i, "Sprouts"],
  [/fresh market/i, "The Fresh Market"],
  [/\bmarket basket/i, "Market Basket"],
  [/\bwinn.dixie/i, "Winn-Dixie"],
  [/\bpiggly wiggly/i, "Piggly Wiggly"],
  [/smart & final/i, "Smart & Final"],
  [/\bwal.?mart\b/i, "Walmart"],
  [/\btarget\b/i, "Target"],
  [/dollar general/i, "Dollar General"],
  [/dollar tree/i, "Dollar Tree"],
  [/family dollar/i, "Family Dollar"],
  [/five below/i, "Five Below"],

  // ── Home Improvement & Hardware ───────────────────────────────────────────
  [/home depot/i, "Home Depot"],
  [/\blowe.?s\b/i, "Lowe's"],
  [/ace hardware/i, "Ace Hardware"],
  [/menards/i, "Menards"],
  [/true value/i, "True Value"],
  [/ikea/i, "IKEA"],
  [/wayfair/i, "Wayfair"],
  [/\boverstock\b/i, "Overstock"],

  // ── Pharmacy & Health ─────────────────────────────────────────────────────
  [/\bcvs\b/i, "CVS"],
  [/walgreens/i, "Walgreens"],
  [/rite aid/i, "Rite Aid"],
  [/\bwalmartpharm/i, "Walmart Pharmacy"],
  [/express scripts/i, "Express Scripts"],
  [/caremark/i, "CVS Caremark"],
  [/optum rx/i, "OptumRx"],
  [/hims\b|hers\b|forhims/i, "Hims & Hers"],
  [/ro pharmacy|getroman/i, "Ro"],
  [/noom/i, "Noom"],
  [/weight watchers|ww\b/i, "WeightWatchers"],
  [/calm\.com/i, "Calm"],
  [/headspace/i, "Headspace"],

  // ── Gas Stations ──────────────────────────────────────────────────────────
  [/7.eleven/i, "7-Eleven"],
  [/\bshell\b/i, "Shell"],
  [/chevron/i, "Chevron"],
  [/\bexxon\b/i, "Exxon"],
  [/mobil/i, "Mobil"],
  [/\bbp\b/i, "BP"],
  [/sunoco/i, "Sunoco"],
  [/marathon/i, "Marathon"],
  [/\bcasey.?s\b/i, "Casey's"],
  [/circle k/i, "Circle K"],
  [/\bpilot\b.*travel|pilot flying/i, "Pilot"],
  [/love.?s travel/i, "Love's"],
  [/speedway/i, "Speedway"],
  [/\barco\b/i, "Arco"],
  [/wawa/i, "Wawa"],
  [/sheetz/i, "Sheetz"],
  [/kwik trip/i, "Kwik Trip"],
  [/racetrac/i, "RaceTrac"],
  [/murphyusa/i, "Murphy USA"],

  // ── Telecom & Internet ────────────────────────────────────────────────────
  [/at&t|att\b/i, "AT&T"],
  [/verizon/i, "Verizon"],
  [/t.?mobile/i, "T-Mobile"],
  [/comcast|xfinity/i, "Xfinity"],
  [/\bspectrum\b/i, "Spectrum"],
  [/\bcox\b.*comm|cox communications/i, "Cox"],
  [/mediacom/i, "Mediacom"],
  [/frontier/i, "Frontier"],
  [/centurylink|lumen/i, "CenturyLink"],
  [/earthlink/i, "EarthLink"],
  [/mint mobile/i, "Mint Mobile"],
  [/google fi|google.*wireless/i, "Google Fi"],
  [/\bcricket\b/i, "Cricket"],
  [/metro by t.mobile|metropcs/i, "Metro"],
  [/boost mobile/i, "Boost Mobile"],
  [/straight talk/i, "Straight Talk"],
  [/dish network|dish\b/i, "DISH"],
  [/directv/i, "DirecTV"],

  // ── Insurance ─────────────────────────────────────────────────────────────
  [/\bgeico\b/i, "GEICO"],
  [/state farm/i, "State Farm"],
  [/allstate/i, "Allstate"],
  [/progressive/i, "Progressive"],
  [/farmers insurance|farmers\b/i, "Farmers"],
  [/liberty mutual/i, "Liberty Mutual"],
  [/nationwide/i, "Nationwide"],
  [/usaa/i, "USAA"],
  [/travelers insurance|travelers\b/i, "Travelers"],
  [/aetna/i, "Aetna"],
  [/united.*health|unitedhealthcare/i, "UnitedHealth"],
  [/blue cross|anthem/i, "Blue Cross"],
  [/cigna/i, "Cigna"],
  [/humana/i, "Humana"],
  [/oscar health/i, "Oscar"],
  [/metlife/i, "MetLife"],
  [/new york life/i, "NY Life"],
  [/northwestern mutual/i, "NW Mutual"],

  // ── Fitness ───────────────────────────────────────────────────────────────
  [/peloton/i, "Peloton"],
  [/planet fitness/i, "Planet Fitness"],
  [/la fitness/i, "LA Fitness"],
  [/crunch fitness/i, "Crunch Fitness"],
  [/anytime fitness/i, "Anytime Fitness"],
  [/24 hour fitness/i, "24 Hour Fitness"],
  [/gold.?s gym/i, "Gold's Gym"],
  [/equinox/i, "Equinox"],
  [/classpass/i, "ClassPass"],
  [/orange theory|orangetheory/i, "Orangetheory"],
  [/f45/i, "F45"],
  [/\bymca\b/i, "YMCA"],
  [/\bnike.*train|nike.*run/i, "Nike Training"],
  [/myfitnesspal/i, "MyFitnessPal"],
  [/strava/i, "Strava"],

  // ── Travel ────────────────────────────────────────────────────────────────
  [/\bairbnb\b/i, "Airbnb"],
  [/expedia/i, "Expedia"],
  [/hotels\.com/i, "Hotels.com"],
  [/booking\.com/i, "Booking.com"],
  [/priceline/i, "Priceline"],
  [/kayak/i, "KAYAK"],
  [/hopper/i, "Hopper"],
  [/\bdelta\b/i, "Delta"],
  [/american airlines|aa\b/i, "American Airlines"],
  [/united airlines/i, "United Airlines"],
  [/southwest/i, "Southwest"],
  [/jetblue/i, "JetBlue"],
  [/spirit airlines/i, "Spirit"],
  [/frontier airlines/i, "Frontier Airlines"],
  [/alaska airlines/i, "Alaska Airlines"],
  [/amtrak/i, "Amtrak"],
  [/enterprise rent/i, "Enterprise"],
  [/hertz/i, "Hertz"],
  [/avis/i, "Avis"],
  [/budget rent/i, "Budget"],
  [/national car/i, "National"],

  // ── Shopping ──────────────────────────────────────────────────────────────
  [/amazon|amzn/i, "Amazon"],
  [/ebay/i, "eBay"],
  [/chewy/i, "Chewy"],
  [/etsy/i, "Etsy"],
  [/\bshein\b/i, "SHEIN"],
  [/\bzara\b/i, "Zara"],
  [/h&m|h and m\b/i, "H&M"],
  [/\bgap\b/i, "Gap"],
  [/old navy/i, "Old Navy"],
  [/\bbana.*republic/i, "Banana Republic"],
  [/\bnordstrom\b/i, "Nordstrom"],
  [/\bmacy.?s\b/i, "Macy's"],
  [/\bkohl.?s\b/i, "Kohl's"],
  [/jcpenney/i, "JCPenney"],
  [/\bthrift\b|goodwill/i, "Goodwill"],
  [/best buy/i, "Best Buy"],
  [/\bnewegg\b/i, "Newegg"],
  [/\bwish\b/i, "Wish"],
  [/temu/i, "Temu"],
  [/poshmark/i, "Poshmark"],
  [/mercari/i, "Mercari"],
  [/\bfashion nova/i, "Fashion Nova"],
  [/\bpetco\b/i, "Petco"],
  [/petsmart/i, "PetSmart"],
  [/autozone/i, "AutoZone"],
  [/o.?reilly auto/i, "O'Reilly"],
  [/advance auto/i, "Advance Auto"],
  [/napa auto/i, "NAPA Auto"],

  // ── Social & Other ────────────────────────────────────────────────────────
  [/twitter|x\.com/i, "X (Twitter)"],
  [/facebook|meta\b/i, "Meta"],
  [/instagram/i, "Instagram"],
  [/tiktok/i, "TikTok"],
  [/snapchat/i, "Snapchat"],
  [/pinterest/i, "Pinterest"],
  [/reddit/i, "Reddit"],
];

// Maps clean merchant name → domain for Clearbit logo
export const MERCHANT_DOMAINS: Record<string, string> = {
  // Streaming
  "Netflix": "netflix.com",
  "Hulu": "hulu.com",
  "Disney+": "disneyplus.com",
  "HBO Max": "max.com",
  "Paramount+": "paramountplus.com",
  "Peacock": "peacocktv.com",
  "Crunchyroll": "crunchyroll.com",
  "Starz": "starz.com",
  "Showtime": "showtime.com",
  "Discovery+": "discoveryplus.com",
  "Fubo": "fubo.tv",
  "Sling TV": "sling.com",
  "YouTube": "youtube.com",
  "YouTube Premium": "youtube.com",
  "Twitch": "twitch.tv",
  "Plex": "plex.tv",
  "ESPN+": "espnplus.com",
  "Apple TV+": "tv.apple.com",
  "Shudder": "shudder.com",
  "MUBI": "mubi.com",

  // Music
  "Spotify": "spotify.com",
  "Apple Music": "music.apple.com",
  "Amazon Music": "music.amazon.com",
  "Tidal": "tidal.com",
  "Pandora": "pandora.com",
  "SiriusXM": "siriusxm.com",
  "Deezer": "deezer.com",
  "SoundCloud": "soundcloud.com",

  // Cloud & Apple
  "iCloud": "icloud.com",
  "Apple": "apple.com",
  "Google One": "one.google.com",
  "Google": "google.com",
  "Microsoft 365": "microsoft.com",
  "Microsoft": "microsoft.com",
  "Dropbox": "dropbox.com",
  "Box": "box.com",
  "OneDrive": "onedrive.live.com",

  // Software & Productivity
  "Adobe": "adobe.com",
  "GitHub": "github.com",
  "Zoom": "zoom.us",
  "Slack": "slack.com",
  "Notion": "notion.so",
  "Figma": "figma.com",
  "Canva": "canva.com",
  "Grammarly": "grammarly.com",
  "LastPass": "lastpass.com",
  "1Password": "1password.com",
  "Dashlane": "dashlane.com",
  "NordVPN": "nordvpn.com",
  "ExpressVPN": "expressvpn.com",
  "Surfshark": "surfshark.com",
  "ChatGPT": "openai.com",
  "Midjourney": "midjourney.com",
  "Asana": "asana.com",
  "Trello": "trello.com",
  "Monday.com": "monday.com",
  "Salesforce": "salesforce.com",
  "HubSpot": "hubspot.com",
  "Mailchimp": "mailchimp.com",
  "Squarespace": "squarespace.com",
  "Wix": "wix.com",
  "WordPress": "wordpress.com",
  "GoDaddy": "godaddy.com",
  "Namecheap": "namecheap.com",
  "Cloudflare": "cloudflare.com",
  "Heroku": "heroku.com",
  "DigitalOcean": "digitalocean.com",
  "AWS": "aws.amazon.com",
  "Shopify": "shopify.com",
  "Duolingo": "duolingo.com",
  "Audible": "audible.com",
  "Kindle": "amazon.com",
  "Skillshare": "skillshare.com",
  "MasterClass": "masterclass.com",
  "Coursera": "coursera.org",
  "Udemy": "udemy.com",
  "LinkedIn": "linkedin.com",

  // Gaming
  "PlayStation": "playstation.com",
  "Xbox": "xbox.com",
  "Nintendo": "nintendo.com",
  "Steam": "store.steampowered.com",
  "Epic Games": "epicgames.com",
  "Blizzard": "blizzard.com",
  "EA": "ea.com",
  "Ubisoft": "ubisoft.com",

  // Payments & Finance
  "Venmo": "venmo.com",
  "PayPal": "paypal.com",
  "Cash App": "cash.app",
  "Zelle": "zellepay.com",
  "Klarna": "klarna.com",
  "Afterpay": "afterpay.com",
  "Affirm": "affirm.com",
  "Coinbase": "coinbase.com",
  "Robinhood": "robinhood.com",
  "Fidelity": "fidelity.com",
  "Charles Schwab": "schwab.com",
  "Vanguard": "vanguard.com",
  "Betterment": "betterment.com",
  "Wealthfront": "wealthfront.com",
  "SoFi": "sofi.com",
  "Acorns": "acorns.com",
  "Stash": "stash.com",

  // Banks
  "Chase": "chase.com",
  "Bank of America": "bankofamerica.com",
  "Wells Fargo": "wellsfargo.com",
  "Capital One": "capitalone.com",
  "Discover": "discover.com",
  "Citi": "citi.com",
  "Amex": "americanexpress.com",
  "US Bank": "usbank.com",
  "PNC": "pnc.com",
  "TD Bank": "td.com",
  "Ally": "ally.com",
  "Synchrony": "synchrony.com",

  // Ride Share & Delivery
  "Uber Eats": "ubereats.com",
  "Uber": "uber.com",
  "Lyft": "lyft.com",
  "DoorDash": "doordash.com",
  "GrubHub": "grubhub.com",
  "Instacart": "instacart.com",
  "Postmates": "postmates.com",
  "GoPuff": "gopuff.com",
  "Shipt": "shipt.com",
  "Fetch": "fetchrewards.com",

  // Fast Food
  "Chipotle": "chipotle.com",
  "McDonald's": "mcdonalds.com",
  "Starbucks": "starbucks.com",
  "Chick-fil-A": "chick-fil-a.com",
  "Dunkin'": "dunkindonuts.com",
  "Subway": "subway.com",
  "Domino's": "dominos.com",
  "Pizza Hut": "pizzahut.com",
  "Taco Bell": "tacobell.com",
  "Burger King": "bk.com",
  "Wendy's": "wendys.com",
  "Panda Express": "pandaexpress.com",
  "Popeyes": "popeyes.com",
  "Sonic": "sonicdrivein.com",
  "Wingstop": "wingstop.com",
  "Shake Shack": "shakeshack.com",
  "Five Guys": "fiveguys.com",
  "Whataburger": "whataburger.com",
  "In-N-Out": "in-n-out.com",
  "Jack in the Box": "jackinthebox.com",
  "Arby's": "arbys.com",
  "Hardee's": "hardees.com",
  "Del Taco": "deltaco.com",
  "Qdoba": "qdoba.com",
  "Moe's": "moes.com",
  "Panera Bread": "panerabread.com",
  "Jersey Mike's": "jerseymikes.com",
  "Firehouse Subs": "firehousesubs.com",
  "Jimmy John's": "jimmyjohns.com",
  "KFC": "kfc.com",

  // Sit-Down
  "Olive Garden": "olivegarden.com",
  "Applebee's": "applebees.com",
  "IHOP": "ihop.com",
  "Denny's": "dennys.com",
  "Waffle House": "wafflehouse.com",
  "Buffalo Wild Wings": "buffalowildwings.com",
  "Outback": "outback.com",
  "Red Lobster": "redlobster.com",
  "Texas Roadhouse": "texasroadhouse.com",
  "LongHorn": "longhornsteakhouse.com",
  "Red Robin": "redrobin.com",
  "Chili's": "chilis.com",
  "TGI Fridays": "tgifridays.com",
  "Cracker Barrel": "crackerbarrel.com",
  "Cheesecake Factory": "thecheesecakefactory.com",

  // Coffee
  "Dutch Bros": "dutchbros.com",
  "Coffee Bean": "coffeebean.com",
  "Peet's": "peets.com",
  "Caribou Coffee": "cariboucoffee.com",
  "Tim Hortons": "timhortons.com",

  // Grocery & Retail
  "Whole Foods": "wholefoodsmarket.com",
  "Trader Joe's": "traderjoes.com",
  "Kroger": "kroger.com",
  "Costco": "costco.com",
  "Sam's Club": "samsclub.com",
  "Aldi": "aldi.us",
  "Publix": "publix.com",
  "H-E-B": "heb.com",
  "Meijer": "meijer.com",
  "Wegmans": "wegmans.com",
  "Safeway": "safeway.com",
  "Albertsons": "albertsons.com",
  "Food Lion": "foodlion.com",
  "Giant": "giantfood.com",
  "Stop & Shop": "stopandshop.com",
  "Sprouts": "sprouts.com",
  "Winn-Dixie": "winndixie.com",
  "Walmart": "walmart.com",
  "Target": "target.com",
  "Dollar General": "dollargeneral.com",
  "Dollar Tree": "dollartree.com",
  "Family Dollar": "familydollar.com",
  "Five Below": "fivebelow.com",

  // Home Improvement
  "Home Depot": "homedepot.com",
  "Lowe's": "lowes.com",
  "Ace Hardware": "acehardware.com",
  "Menards": "menards.com",
  "IKEA": "ikea.com",
  "Wayfair": "wayfair.com",

  // Pharmacy & Health
  "CVS": "cvs.com",
  "Walgreens": "walgreens.com",
  "Rite Aid": "riteaid.com",
  "Hims & Hers": "forhims.com",
  "Noom": "noom.com",
  "WeightWatchers": "weightwatchers.com",
  "Calm": "calm.com",
  "Headspace": "headspace.com",

  // Gas
  "7-Eleven": "7-eleven.com",
  "Shell": "shell.com",
  "Chevron": "chevron.com",
  "Exxon": "exxon.com",
  "Mobil": "mobil.com",
  "BP": "bp.com",
  "Sunoco": "sunoco.com",
  "Marathon": "marathonbrand.com",
  "Casey's": "caseys.com",
  "Circle K": "circlek.com",
  "Pilot": "pilotflyingj.com",
  "Love's": "loves.com",
  "Speedway": "speedway.com",
  "Wawa": "wawa.com",
  "Sheetz": "sheetz.com",
  "Kwik Trip": "kwiktrip.com",

  // Telecom
  "AT&T": "att.com",
  "Verizon": "verizon.com",
  "T-Mobile": "t-mobile.com",
  "Xfinity": "xfinity.com",
  "Spectrum": "spectrum.com",
  "Cox": "cox.com",
  "Mediacom": "mediacomcable.com",
  "Frontier": "frontier.com",
  "CenturyLink": "centurylink.com",
  "Mint Mobile": "mintmobile.com",
  "Google Fi": "fi.google.com",
  "Cricket": "cricketwireless.com",
  "Metro": "metrobyt-mobile.com",
  "Boost Mobile": "boostmobile.com",
  "DISH": "dish.com",
  "DirecTV": "directv.com",

  // Insurance
  "GEICO": "geico.com",
  "State Farm": "statefarm.com",
  "Allstate": "allstate.com",
  "Progressive": "progressive.com",
  "Farmers": "farmers.com",
  "Liberty Mutual": "libertymutual.com",
  "Nationwide": "nationwide.com",
  "USAA": "usaa.com",
  "Travelers": "travelers.com",
  "Aetna": "aetna.com",
  "UnitedHealth": "uhc.com",
  "Blue Cross": "bcbs.com",
  "Cigna": "cigna.com",
  "Humana": "humana.com",
  "Oscar": "hioscar.com",
  "MetLife": "metlife.com",

  // Fitness
  "Peloton": "onepeloton.com",
  "Planet Fitness": "planetfitness.com",
  "LA Fitness": "lafitness.com",
  "Crunch Fitness": "crunch.com",
  "Anytime Fitness": "anytimefitness.com",
  "24 Hour Fitness": "24hourfitness.com",
  "Gold's Gym": "goldsgym.com",
  "Equinox": "equinox.com",
  "ClassPass": "classpass.com",
  "Orangetheory": "orangetheory.com",
  "YMCA": "ymca.net",
  "MyFitnessPal": "myfitnesspal.com",
  "Strava": "strava.com",

  // Travel
  "Airbnb": "airbnb.com",
  "Expedia": "expedia.com",
  "Hotels.com": "hotels.com",
  "Booking.com": "booking.com",
  "Priceline": "priceline.com",
  "KAYAK": "kayak.com",
  "Hopper": "hopper.com",
  "Delta": "delta.com",
  "American Airlines": "aa.com",
  "United Airlines": "united.com",
  "Southwest": "southwest.com",
  "JetBlue": "jetblue.com",
  "Spirit": "spirit.com",
  "Frontier Airlines": "flyfrontier.com",
  "Alaska Airlines": "alaskaair.com",
  "Amtrak": "amtrak.com",
  "Enterprise": "enterprise.com",
  "Hertz": "hertz.com",
  "Avis": "avis.com",

  // Shopping
  "Amazon": "amazon.com",
  "eBay": "ebay.com",
  "Chewy": "chewy.com",
  "Etsy": "etsy.com",
  "SHEIN": "shein.com",
  "Zara": "zara.com",
  "H&M": "hm.com",
  "Gap": "gap.com",
  "Old Navy": "oldnavy.com",
  "Banana Republic": "bananarepublic.com",
  "Nordstrom": "nordstrom.com",
  "Macy's": "macys.com",
  "Kohl's": "kohls.com",
  "JCPenney": "jcpenney.com",
  "Goodwill": "goodwill.org",
  "Best Buy": "bestbuy.com",
  "Newegg": "newegg.com",
  "Temu": "temu.com",
  "Poshmark": "poshmark.com",
  "Mercari": "mercari.com",
  "Petco": "petco.com",
  "PetSmart": "petsmart.com",
  "AutoZone": "autozone.com",
  "O'Reilly": "oreillyauto.com",
  "Advance Auto": "advanceautoparts.com",
  "NAPA Auto": "napaonline.com",

  // Social
  "X (Twitter)": "x.com",
  "Meta": "meta.com",
  "TikTok": "tiktok.com",
  "Snapchat": "snapchat.com",
  "Pinterest": "pinterest.com",
  "Reddit": "reddit.com",
};

export function simplifyName(raw: string | null | undefined): string {
  if (!raw) return "Unknown";

  for (const [pattern, cleanName] of MERCHANT_MAP) {
    if (pattern.test(raw)) return cleanName;
  }

  let clean = raw
    .replace(/\*/g, " ")
    .replace(/\b\d{7,}\b/g, "")
    .replace(/\s+#\d+/g, "")
    .replace(/\.(com|net|org|io)\b/gi, "")
    .replace(/\b(LLC|INC|CORP|LTD|CO)\b\.?/gi, "")
    .replace(/\s{2,}/g, " ")
    .trim();

  return clean
    .split(" ")
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ") || raw;
}

export function getMerchantDomain(cleanName: string): string | null {
  return MERCHANT_DOMAINS[cleanName] ?? null;
}
